"""Add emoji to document

Revision ID: 015ec0f3c03d
Revises: 6e4a265ff0ec
Create Date: 2026-02-09 23:49:35.832530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015ec0f3c03d'
down_revision: Union[str, Sequence[str], None] = '6e4a265ff0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('emoji', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'emoji')
    # ### end Alembic commands ###
