"""Add embedding blob to chunk cache

Revision ID: 6e4a265ff0ec
Revises: 9762af73e1c5
Create Date: 2026-02-06 23:04:13.940756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4a265ff0ec'
down_revision: Union[str, Sequence[str], None] = '9762af73e1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_cache', sa.Column('embedding', sa.LargeBinary(), nullable=False))
    op.add_column('chunk_cache', sa.Column('model_name', sa.String(), nullable=True))
    op.drop_column('chunk_cache', 'ref_doc_id')
    op.drop_column('chunk_cache', 'text_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_cache', sa.Column('text_content', sa.TEXT(), nullable=True))
    op.add_column('chunk_cache', sa.Column('ref_doc_id', sa.VARCHAR(), nullable=False))
    op.drop_column('chunk_cache', 'model_name')
    op.drop_column('chunk_cache', 'embedding')
    # ### end Alembic commands ###
