"""Initial tables

Revision ID: 9762af73e1c5
Revises: 
Create Date: 2026-02-06 23:00:54.283241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9762af73e1c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_artifacts_hash'), 'artifacts', ['hash'], unique=False)
    op.create_table('chunk_cache',
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('ref_doc_id', sa.String(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('text_hash')
    )
    op.create_index(op.f('ix_chunk_cache_text_hash'), 'chunk_cache', ['text_hash'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notebook_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_msg', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_hash'], ['artifacts.hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_notebook_id'), 'documents', ['notebook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_notebook_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chunk_cache_text_hash'), table_name='chunk_cache')
    op.drop_table('chunk_cache')
    op.drop_index(op.f('ix_artifacts_hash'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
